"""Build the ScrollQ leaderboard page from volumes.json."""

from __future__ import annotations

import argparse
import html
import json
import os

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ScrollQ — Vesuvius scroll volume quality leaderboard</title>
<style>
body{{font-family:-apple-system,system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem;color:#1a1a1a}}
table{{border-collapse:collapse;width:100%;font-size:.85rem}}
th,td{{border:1px solid #ddd;padding:.35rem .5rem;text-align:right}}
th:first-child,td:first-child,td:nth-child(2){{text-align:left}}
th{{background:#f5f5f5;position:sticky;top:0}}
tr:nth-child(even){{background:#fafafa}}
.score{{font-weight:700}}
.warn{{color:#b35400;font-weight:700}}
code{{font-size:.78rem}}
.note{{background:#fff8e6;border:1px solid #e6c200;padding:.8rem 1rem;border-radius:6px}}
</style></head><body>
<h1>ScrollQ leaderboard</h1>
<p>Data-quality triage for Vesuvius scroll volumes: <strong>train on the best
first.</strong> Each volume's full-resolution level is sampled (4 &times;
128&sup3; chunks), decoded, and scored 0&ndash;100 on signal presence, texture
energy, dynamic range, and acquisition-artifact penalties. Method and weights
are published in the <a href="https://github.com/Svyable/scrollq">repo</a> —
re-weight it however you like.</p>
<div class="note"><strong>Honest scope:</strong> this is a triage signal, not a
readability claim. It does not detect ink and does not predict which scroll
will read. It tells you which volumes have the healthiest voxels, so
segmentation effort goes where the data is strongest.</div>
<p>{n} volumes scored, {t}.</p>
<table><thead><tr>
<th>#</th><th>volume</th><th>score</th><th>signal/40</th><th>texture/30</th>
<th>dynamic/20</th><th>sat pen</th><th>dead-slice pen</th>
<th>nonzero</th><th>grad</th><th>dyn range</th><th>dead slices</th>
{cov_head}
</tr></thead><tbody>
{rows}
</tbody></table>
{cov_note}
<p><small>Generated by <a href="https://github.com/Svyable/scrollq">ScrollQ</a>
from public dl.ash2txt.org volumes. Scores are heuristic and published with
their components — audit the weights, don't worship the ranking.</small></p>
</body></html>
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--coverage", default=None,
                    help="coverage.json from scrollq-coverage")
    args = ap.parse_args()
    with open(args.inp, encoding="utf-8") as fh:
        vols = json.load(fh)
    cov = {}
    if args.coverage:
        with open(args.coverage, encoding="utf-8") as fh:
            cov = json.load(fh)
    ok = [v for v in vols if v.get("ok")]
    has_cov = bool(cov)
    rows = []
    for i, v in enumerate(ok, 1):
        c = v["components"]
        m = v["metrics"]
        parts = v["root"].split("/")
        name = html.escape(
            f"{parts[-3]}/{parts[-1].replace('.zarr', '')}")
        dead = m.get("dead_slices", 0)
        dead_cell = (f'<span class="warn">{dead}</span>' if dead
                     else "0")
        extra = ""
        if has_cov:
            cc = cov.get(v["root"], {})
            ink = cc.get("ink_labels", 0)
            seg = cc.get("segments", 0)
            flag = ("🎯 label next" if cc.get("label_next") else "")
            extra = (f"<td>{ink}</td><td>{seg}</td>"
                     f"<td>{flag}</td>")
        rows.append(
            f"<tr><td>{i}</td><td><code>{name}</code></td>"
            f'<td class="score">{v["score"]:.1f}</td>'
            f"<td>{c['signal_40']:.1f}</td><td>{c['texture_30']:.1f}</td>"
            f"<td>{c['dynamic_20']:.1f}</td><td>{c['pen_sat']:.1f}</td>"
            f"<td>{c['pen_dead']:.1f}</td>"
            f"<td>{m['nonzero_frac']:.3f}</td>"
            f"<td>{m['grad_energy']:.2f}</td>"
            f"<td>{m['dyn_range']:.0f}</td><td>{dead_cell}</td>"
            f"{extra}</tr>")
    import datetime
    stamp = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%d %H:%M UTC")
    cov_head = ("<th>ink labels</th><th>segments</th><th></th>"
                if has_cov else "")
    cov_note = ("""<div class="note"><strong>🎯 label next:</strong> top-quartile
quality scrolls with zero ink-detection labels in the open-data S3 bucket —
all 70 published ink labels sit on PHercParis4 (quality rank 13 of 39).
Segmentation/labeling effort goes furthest at the top of this list.</div>"""
                if has_cov else "")
    page = PAGE.format(n=len(ok), t=stamp, rows="\n".join(rows),
                       cov_head=cov_head, cov_note=cov_note)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(page)
    print(f"wrote {args.out} ({len(ok)} volumes)")
